### PR TITLE
Documentation: Edited user guide

### PR DESCRIPTION
**Pull request by lyhvictoria**
Added in browser section
Edited list and select command to show UI changes.
Shifted autocomplete and browser function to Features in v1.2

### CODE REVIEW

**Review by Kennard123661 — CHANGES_REQUESTED** [review]
You do not need to edit the add commands and edit commands, you can revert those changes (i'm doing that haha :X) and cuz the add command doesnt need a status input, it defaults to "pending" if there's no status. Then please update the image of Ark too.

**Comment by lyhvictoria** [comment]
Ok! I'll do that

**Comment by lyhvictoria** [comment]
resolved conflicts ^

**Review by Kennard123661 — APPROVED** [review]
looks good @Kowalski985

**Review by ktnc985 — APPROVED** [review]

**Pull request merged**
