### PR TITLE
UI: Enhancement

### PR DESCRIPTION
**Pull request by lyhvictoria**
1. added color to tags
2. added color for unknown command
3. added number of people in list to status footer

### CODE REVIEW

**Review by Kennard123661 — CHANGES_REQUESTED** [review]
Meet later to discuss your code and why its failing the tests.

**Comment by lyhvictoria** [comment]
Now I'm totally confused why help window test is failing when I've never touch help window at all. New day, new problems :D

**Comment by fustilio** [comment]
@vicisapotato You're only failing cause of a minor bug: one of your lines has too many characters, just break it up and we're good. (i hope)

**Review by Kennard123661 — APPROVED** [review]

**Comment by Kennard123661** [comment]
Looks good! Will merge this in

**Pull request merged**
